server:
  port: 8081

spring:
  application:
    name: base

  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/main
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
keycloak:
  auth-server-url: http://localhost:8080
  realm: main
  client-id: myClientId
  credentials.secret: 2Ioaw7g0QaowFp2Tk4DBtRLuHQfkRvlc
